version: '3.8'

services:
  arniva-payment:
    image: node:24-alpine
    working_dir: /app
    environment:
      - NPM_TOKEN=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
    volumes:
      - .:/app
      - ./.npmrc:/app/.npmrc
    ports:
      - "5173:5173"
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm run dev --host 0.0.0.0"
