name: Pull and Restart Test Version

on:
  workflow_run: 
    workflows: ["Dockerize Test Version and Push to Docker Hub"]
    types:
      - completed

jobs:
  pull-and-restart:
    name: Pull and Restart Test Version
    runs-on: ubuntu-latest
    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY_TEST }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{secrets.SSH_HOST_TEST}} >> ~/.ssh/known_hosts
      - name: connect and pull
        run: ssh ${{secrets.SSH_USER_TEST}}@${{secrets.SSH_HOST_TEST}} "cd /opt/docker/${{github.repository}} && docker compose pull && docker compose up -d"
      - name: cleanups
        run: |
          rm ~/.ssh/id_rsa
          ssh-keygen -R ${{secrets.SSH_HOST_TEST}}